apiVersion: 1

datasources:
- name: Elasticsearch
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://elasticsearch:9200
  basicAuth: true
  basicAuthUser: elastic
  withCredentials: true
  isDefault: false
  database: "[filebeat-]*"
  jsonData:
     tlsSkipVerify: true
     timeInterval: 10s
     esVersion: 70
     timeField: "@timestamp"
     interval: Daily
     logMessageField: message
     logLevelField: fields.level
     dataLinks:
     - datasourceUid: tempo
       field: traceID
       url: $${__value.raw}
  secureJsonData:
     basicAuthPassword: changeme
     version: 1
  editable: true
